### ISSUE TITLE
Can't start the daemon manually on a fresh ubuntu 16.04 (VPS)

### ISSUE THREAD

**Issue by oxmah** [phoreproject/Phore#15]
This issue tracker is only for technical issues related to Phore Core.
General Phore questions and/or support requests and are best directed to the [Phore Discord](https://discord.gg/sbgdcdv).

### Describe the issue

Impossible to start the daemon through phored -daemon or ./phored -daemon

Bash report that the file doesn't exist, even if it does. 

#### If so, please list the steps to reproduce below:
1. 
2.
3.

### Expected behavior
Tell us what should happen

The daemon should start.

### Actual behavior
Tell us what happens instead

The system can't start (see) it. 

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of Phore Core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package.

1.2.2

### Machine specs:
- OS: Ubuntu 16.04 on a Vultre server. All updated and fresh. 
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log`, `db.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by tohsnoom** [comment]
mathiewarbezhermoso, without more information, my first guess would be a permissions issue, perhaps the file doesn't have execute permissions. Could you try:

```chmod a+x phored```

And then try to launch phored?

Otherwise, how was phore installed on the machine? Our masternode installation scripts generally put the files in /usr/local/bin, but that should still work if you say phored -daemon since /usr/local/bin is on the default path.

I just tried to replicate the issue by simply downloading  and uncompressing the linux package here:

https://github.com/phoreproject/Phore/releases/download/v1.2.2/phore-1.2.2-x86_64-linux-gnu.tar.gz

I was unsuccessful in replicating the issue--at first it gave me an error saying that I needed to add values for rpcuser and rpcpassword to phore.conf, but it was very descriptive about what you needed to do. After adding those values, phored -daemon worked for me.
